services:
  guvenli-app:
    image: guvensiz-app:v2
    container_name: kale-app-otomatik
    # GÜVENLİK AYARLARI (Hardening)
    read_only: true       # Dosya sistemi salt okunur (Hacker dosya yazamaz)
    cap_drop:
      - ALL               # Tüm Linux yeteneklerini çöpe at